Repository codeforpdx/tenantfirstaid, pull requests merged in 2025-05, with the labels that each got.

#17 [New Feature] - Refocus user input field
  frontend/src/Chat.tsx
Labels: enhancement

#20 [Bug] - Include missing dotenv dependency
  backend/pyproject.toml
  backend/uv.lock
Labels: bug

#21 [Prompt Update] - Chatbot is not a lawyer
  backend/tenantfirstaid/shared.py
Labels: enhancement

#31 Introduce Tailwind CSS
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Chat.tsx
  frontend/src/Feedback.tsx
  frontend/src/PromptEditor.tsx
  frontend/src/style.css
  frontend/vite.config.ts
Labels: enhancement

#37 feat: first pass at redis session cache
  .github/workflows/deploy.yml
  .gitignore
  backend/.env.example
  backend/pyproject.toml
  backend/tenantfirstaid/app.py
  backend/tenantfirstaid/chat.py
  backend/tenantfirstaid/prepare_training.py
  backend/tenantfirstaid/session.py
  backend/tenantfirstaid/shared.py
  backend/uv.lock
Labels: enhancement, backend

#40 Feature: Export messages button
  frontend/src/Chat.tsx
  frontend/src/pages/Chat/components/ExportMessagesButton.tsx
  frontend/src/pages/Chat/utils/exportHelper.ts
Labels: enhancement

#41 Feat: message history
  backend/tenantfirstaid/app.py
  frontend/src/Chat.tsx
Labels: enhancement, backend, frontend

#51 Feature: Input field transition
  backend/.env.example
  backend/uv.lock
  frontend/src/Chat.tsx
  frontend/src/Feedback.tsx
  frontend/src/PromptEditor.tsx
  frontend/src/pages/Chat/components/ExportMessagesButton.tsx
  frontend/src/style.css
Labels: enhancement

#57 Update message size within chat window
  frontend/src/Chat.tsx
Labels: frontend

#63 Bug fix for Chat and MessageWindow
  frontend/src/Chat.tsx
  frontend/src/pages/Chat/components/MessageContent.tsx
  frontend/src/pages/Chat/components/MessageWindow.tsx
Labels: bug, frontend

#66 Move sessionid to React Context
  frontend/src/App.tsx
  frontend/src/contexts/SessionContext.tsx
  frontend/src/hooks/useSession.tsx
  frontend/src/pages/Chat/components/InputField.tsx
  frontend/src/pages/Chat/components/MessageFeedback.tsx
  frontend/src/pages/Chat/components/MessageWindow.tsx
Labels: enhancement

#69 Minor styling updates and refactoring for mobile
  frontend/src/Chat.tsx
  frontend/src/pages/Chat/components/ExportMessagesButton.tsx
  frontend/src/pages/Chat/components/MessageWindow.tsx
Labels: enhancement, frontend

#72 Feature: Migrate to React Query
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Chat.tsx
  frontend/src/hooks/useMessages.tsx
  frontend/src/main.tsx
  frontend/src/pages/Chat/components/ExportMessagesButton.tsx
  frontend/src/pages/Chat/components/InputField.tsx
  frontend/src/pages/Chat/components/MessageContent.tsx
  frontend/src/pages/Chat/components/MessageFeedback.tsx
  frontend/src/pages/Chat/components/MessageWindow.tsx
  frontend/src/pages/Chat/utils/exportHelper.ts
Labels: enhancement, frontend

#78 Bug Fix: Chat history sync issue
  frontend/src/hooks/useMessages.tsx
Labels: bug

#79 add navbar and move export button
  frontend/src/AboutPage.tsx
  frontend/src/App.tsx
  frontend/src/Chat.tsx
  frontend/src/pages/Chat/components/ExportMessagesButton.tsx
  frontend/src/pages/Chat/components/MessageWindow.tsx
  frontend/src/pages/Chat/components/Navbar.tsx
Labels: frontend
